### ISSUE TITLE
redmine 2.5.2 error

### ISSUE THREAD

**Issue by rkuryk** [keeps/redmine_email_notification_content_filter#10]
Plugin appears to be broken with the latest version of redmine, see exception from log file below:

Completed 500 Internal Server Error in 621.0ms

ArgumentError (wrong number of arguments calling `issue_add_with_email_filter` (3 for 1)):
  app/models/mailer.rb:423:in `initialize'
  app/models/mailer.rb:446:in`method_missing'
  app/models/mailer.rb:52:in `deliver_issue_add'
  app/models/issue.rb:831:in`each_notification'
  app/models/mailer.rb:51:in `deliver_issue_add'
  app/models/issue.rb:1528:in`send_notification'
  app/models/issue.rb:165:in `create_or_update'
  app/controllers/issues_controller.rb:150:in`create'

**Comment by vmarquet** [comment]
I've fixed the issue for redmine >= 2.6.1 (I've tested up to 3.2.1). I don't really have time to make a proper pull request and manage redmine version check, etc, so I'll just put the code here if somebody is interested.

The bug is due to an intenal API change in Redmine. So you have to replace `lib/mailer_patch.rb` in the plugin by:

```ruby
module MailerPatch
  def self.included(base) # :nodoc:
    base.send(:include, InstanceMethods)

    base.class_eval do
      alias_method_chain :issue_add, :email_filter
      alias_method_chain :issue_edit, :email_filter
    end
  end

  module InstanceMethods

    def issue_add_with_email_filter(issue, to_users, cc_users)
      if Setting.plugin_redmine_email_notification_content_filter['removeDescription']
        issue.description = "(description hidden)"
      end
      if Setting.plugin_redmine_email_notification_content_filter['removeSubject']
        issue.subject = "(subject hidden)"
      end

      issue_add_without_email_filter(issue, to_users, cc_users)
    end

    def issue_edit_with_email_filter(journal, to_users, cc_users)
      issue = journal.journalized.reload

      if Setting.plugin_redmine_email_notification_content_filter['removeDescription']
        issue.description = "(description hidden)"
      end
      if Setting.plugin_redmine_email_notification_content_filter['removeSubject']
        issue.subject = "(subject hidden)"
      end
      if Setting.plugin_redmine_email_notification_content_filter['removeNote']
        journal.notes = "(notes hidden)"
      end

      issue_edit_without_email_filter(journal, to_users, cc_users)
    end
  end
end
```
And then add two files in the plugin: `app/views/mailer/issue_edit.html.erb` : 

```ruby
<% if @journal.private_notes? %>
  (<%= l(:field_private_notes) %>)
<% end %>
<%= l(:text_issue_updated, :id => "##{@issue.id}", :author => h(@journal.user)) %>

<% if !Setting.plugin_redmine_email_notification_content_filter['removeDescription'] && !Setting.plugin_redmine_email_notification_content_filter['removeSubject'] %>
  <ul>
  <% details_to_strings(@journal_details, false, :only_path => false).each do |string| %>
    <li><%= string %></li>
  <% end %>
  </ul>
<% else %>
  <%= "(content hidden)" %>
<% end %>

<%= textilizable(@journal, :notes, :only_path => false) %>
<hr />
<%= render :partial => 'issue', :formats => [:html], :locals => { :issue => @issue, :users => @users, :issue_url => @issue_url } %>
```

and `app/views/mailer/issue_edit.text.erb`:

```ruby
<%= "(#{l(:field_private_notes)}) " if @journal.private_notes? -%>
<%= l(:text_issue_updated, :id => "##{@issue.id}", :author => @journal.user) %>

<% if !Setting.plugin_redmine_email_notification_content_filter['removeDescription'] && !Setting.plugin_redmine_email_notification_content_filter['removeSubject'] %>
  <% details_to_strings(@journal_details, true).each do |string| -%>
    <%= string %>
  <% end -%>
<% else %>
  <%= "(content hidden)" %>
<% end %>

<% if @journal.notes? -%>
<%= @journal.notes %>

<% end -%>
----------------------------------------
<%= render :partial => 'issue', :formats => [:text], :locals => { :issue => @issue, :users => @users, :issue_url => @issue_url } %>
```
