### ISSUE TITLE
redmine 4.x support

### ISSUE THREAD

**Issue by laborb-sb** [keeps/redmine_email_notification_content_filter#11]
Is Redmine 4.0 support planned? I would be very happy about that.
In my eyes the plugin is crucial for the GDPR conformity! and therefore a real blocker for a 4.x update.

Maybe an extract from my log will help.

```
May 10 07:14:13 rake aborted!
May 10 07:14:13 NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
May 10 07:14:13 Did you mean? to_param
May 10 07:14:13 /app/code/plugins/redmine_email_notification_content_filter/init.rb:27:in `<top (required)>'
May 10 07:14:13 /app/data/vendor/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
May 10 07:14:13 /app/data/vendor/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
May 10 07:14:13 /app/code/lib/redmine/plugin.rb:173:in `block in load'
May 10 07:14:13 /app/code/lib/redmine/plugin.rb:164:in `each'
May 10 07:14:13 /app/code/lib/redmine/plugin.rb:164:in `load'
May 10 07:14:13 /app/code/config/initializers/30-redmine.rb:21:in `<top (required)>'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `block in load'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:657:in `block in load_config_initializer'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:170:in `instrument'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:656:in `load_config_initializer'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:613:in `each'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:613:in `block in <class:Engine>'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `each'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
May 10 07:14:13 /app/code/config/environment.rb:14:in `<top (required)>'
May 10 07:14:13 /app/data/vendor/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
May 10 07:14:13 /app/data/vendor/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/railties-5.2.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
May 10 07:14:13 /var/lib/gems/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
```

**Comment by luis100** [comment]
We currently only develop this for internal use, and we have not yet updated to Redmine 4. We will probably do it in the coming months. If you'd like to support the development please contact sales@keep.pt.
